server:
  servlet:
   context-path: '/carro-service/'
   
spring:
  application:
    name: carro-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course-v2
    username: postgres
    password: postgres 
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc: 
        lob.non.contextual-creation: true
    properties:
      hibernate:
        show_sql: true
